apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::569190534191:role/GrafanaAgentAMPRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
rules:
- apiGroups: [""]
  resources: [nodes, nodes/proxy, nodes/metrics, services, endpoints, pods]
  verbs: [get, list, watch]
- apiGroups: [networking.k8s.io]
  resources: [ingresses]
  verbs: [get, list, watch]
- nonResourceURLs: [/metrics, /metrics/cadvisor]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
- kind: ServiceAccount
  name: grafana-agent
  namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: monitoring
data:
  config.alloy: |
    prometheus.scrape "tictactoe" {
      targets = discovery.kubernetes.pods.targets
      forward_to = [prometheus.remote_write.amp.receiver]
      scrape_interval = "30s"
    }

    discovery.kubernetes "pods" {
      role = "pod"
      selectors {
        role = "pod"
        label = "app=tictactoe"
      }
    }

    discovery.relabel "pods" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
        regex = "true"
        action = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_port"]
        target_label = "__address__"
        regex = "(.+)"
        replacement = "${1}"
      }
      rule {
        source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
        target_label = "__address__"
        regex = "([^:]+)(?::\\d+)?;(\\d+)"
        replacement = "$1:$2"
      }
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label = "app"
      }
    }

    prometheus.remote_write "amp" {
      endpoint {
        url = "https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-2b9d7962-96d6-4f42-9531-15c7fe088fc2/api/v1/remote_write"
        sigv4 {
          region = "ap-northeast-2"
        }
      }
      external_labels = {
        cluster = "eks-unique-lofi-goose",
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      serviceAccountName: grafana-agent
      containers:
      - name: alloy
        image: grafana/alloy:v1.4.2
        args:
        - run
        - /etc/alloy/config.alloy
        - --storage.path=/tmp/alloy
        - --server.http.listen-addr=0.0.0.0:12345
        ports:
        - containerPort: 12345
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /etc/alloy
      volumes:
      - name: config
        configMap:
          name: grafana-alloy-config
