apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-operator
  namespace: grafana-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-operator
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "serviceaccounts", "services", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["grafana.integreatly.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-operator
subjects:
- kind: ServiceAccount
  name: grafana-operator
  namespace: grafana-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-operator
  template:
    metadata:
      labels:
        app: grafana-operator
    spec:
      serviceAccountName: grafana-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: grafana-operator
        image: ghcr.io/grafana/grafana-operator:v5.20.0
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=0.0.0.0:9090
        - --zap-encoder=console
        - --zap-log-level=info
        - --leader-elect
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8081
          name: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-operator-metrics
  namespace: grafana-operator
spec:
  selector:
    app: grafana-operator
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
